/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kittu' at '8/4/16 9:52 PM' with Gradle 2.14
 *
 * @author kittu, @date 8/4/16 9:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
